import { UserRole } from './entities/user.entity';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.ADMIN]: [
    'user:manage',
    'user:search',
    'auth:profile',
    'project:read',
    'task:read',
    'member:list',
    'dashboard:read',
  ],
  [UserRole.PROJECT_MANAGER]: [
    'user:search',
    'auth:profile',
    'project:create',
    'project:read',
    'project:close',
    'project:reopen',
    'member:add',
    'member:remove',
    'member:list',
    'leave-request:list',
    'leave-request:manage',
    'task:create',
    'task:read',
    'task:assign',
    'task:archive',
    'task:restore',
    'time-log:create',
    'time-log:manage',
    'time-log:read',
    'dashboard:read',
    'daily-summary:read',
  ],
  [UserRole.TEAM_MEMBER]: [
    'user:search',
    'auth:profile',
    'project:read',
    'member:list',
    'leave-request:create',
    'task:create',
    'task:read',
    'task:archive',
    'task:restore',
    'time-log:create',
    'time-log:manage',
    'time-log:read',
    'dashboard:read',
    'daily-summary:read',
  ],
};
